server:
  port: 8080
  servlet:
    context-path: /api
# Mybatis-Plus 配置
mybatis-plus:
  configuration:
    # 开启下划线到驼峰的自动映射
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
sa-token:
  # token 名称（同时也是 cookie 名称）

  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 259200
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  jwt-secret-key: ${SA_TOKEN_JWT_SECRET:museum}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接本地数据库，请根据你的本地环境修改
    url: jdbc:mysql://localhost:3306/museum?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: akainews
    accessKeyId: ${OSS_ACCESS_KEY_ID}
    accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
